baseURL: http://www.jessekrijthe.com/
disablePathToLower: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
languageCode: en-us
title: Jesse Krijthe
buildDrafts: false
publishDir: build
theme: "theme-jk"
author:
  name: Jesse Krijthe
  email: jkrijthe@gmail.com
permalinks:
  articles: /articles/:filename
taxonomies:
  category: "categories"

markup:
  goldmark:
    renderer:
      unsafe: true
